version: '3.8'

services:
  backend:
    build: backend
    ports:
      - "8080:8080"
    networks:
      - local

  frontend:
    build: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    networks:
      - local
    depends_on:
      - backend

networks:
  local:
    driver: bridge