CREATE SEQUENCE seq_tasks INCREMENT BY 1;

CREATE TABLE tasks (
    id BIGINT NOT NULL PRIMARY KEY,
    title VARCHAR(60) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);